name = "HMMER"
uuid = "59c5aa83-900c-4c4d-b6cc-c9bbbf32a260"
authors = ["JFdCD <jfdecd@icloud.com>"]
version = "1.5.1-DEV"

[deps]
GSL_jll = "1b77fbbe-d8ee-58f0-85f9-836ddc23a7a4"
HMMER_jll = "9a00dd6d-eebd-547e-8f34-c9aea159fd8a"
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"

[compat]
GSL_jll = "~2.7.2"
HMMER_jll = "3.4"
julia = "1.8"
